# 是否启用自动更新
auto-update: true

# 每位玩家可以摆放的区块加载器上限
# 设置为0时无限制
max-chunk-loaders: 8

# 每个区块加载器所需的GPS网络复杂度
gps-complexity-per-loader: 7500

# 是否启用幽灵方块
ghost-blocks: true

# 是否启用神秘科技中的怪物
# 禁用后部分物品的配方会改变，部分物品会被移除
custom-mobs: true
