# 是否启用自动更新
auto-update: true

# 每位玩家可以摆放的区块加载器上限
# 设置为0时无限制
max-chunk-loaders: 8

# 每个区块加载器所需的GPS网络复杂度
gps-complexity-per-loader: 7500

# 是否启用幽灵方块
ghost-blocks: true

# 是否启用神秘科技中的怪物
# 禁用后部分物品的配方会改变，部分物品会被移除
custom-mobs: true

# 填充棒每次可填充的最大方块数量
max-fill-wand-blocks: 4096

# 海绵棒每次可清除的方块数量
max-sponge-wand-blocks: 16384

# 任务所需的生物，将从本列表中随机选择
quest-mobs:
  - BAT
  - BEE
  - BLAZE
  - CAT
  - CHICKEN
  - CAVE_SPIDER
  - COD
  - COW
  - CREEPER
  - DOLPHIN
  - DONKEY
  - DROWNED
  - ENDERMAN
  - GHAST
  - GUARDIAN
  - HOGLIN
  - HUSK
  - HORSE
  - IRON_GOLEM
  - LLAMA
  - MAGMA_CUBE
  - MUSHROOM_COW
  - OCELOT
  - PANDA
  - PARROT
  - PHANTOM
  - PIG
  - PIGLIN
  - PIGLIN_BRUTE
  - PILLAGER
  - POLAR_BEAR
  - PUFFERFISH
  - RABBIT
  - SALMON
  - SHEEP
  - SILVERFISH
  - SKELETON
  - SLIME
  - SNOWMAN
  - SPIDER
  - SQUID
  - STRAY
  - STRIDER
  - TURTLE
  - TROPICAL_FISH
  - WITCH
  - WITHER_SKELETON
  - WOLF
  - ZOGLIN
  - ZOMBIE
  - ZOMBIFIED_PIGLIN
  - FOX